name: nwlon_webcoos_synchronizer
channels:
  - defaults
dependencies:
  - python=3.12
  - pip
  - pip:
    - matplotlib
    - moviepy
    - numpy
    - pandas
    - scikit-learn
    - pytz
    - git+https://github.com/WebCOOS/py-webcoos-client.git#egg=pywebcoos
