name: nwlon_webcoos_synchronizer
channels:
  - defaults
dependencies:
  - python=3.12
  - matplotlib
  - numpy
  - pandas
  - pip
  - scikit-learn
  - pytz
  - pip:
    - moviepy
    - pywebcoos @ git+https://github.com/WebCOOS/py-webcoos-client.git@main#egg=pywebcoos
