name: nwlon_webcoos_synchronizer
channels:
  - defaults
dependencies:
  - python>=3.12
  - matplotlib
  - moviepy
  - numpy
  - pandas
  - scikit-learn
  - pytz
  - pip:
      - git+https://github.com/WebCOOS/py-webcoos-client.git#egg=pywebcoos
